"""Create generated_lineups table for lineup optimizer

Revision ID: 017
Revises: 016
Create Date: 2025-10-30 12:00:00.000000

Description:
Creates generated_lineups table for storing optimized lineups generated by the lineup optimizer.
Stores lineup data as JSONB with player information, salary totals, and optimization settings.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '017'
down_revision = '016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create generated_lineups table."""
    
    # Create enum type for strategy mode (only if it doesn't exist)
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'strategy_mode_enum')"
    )).scalar()
    
    if not result:
        strategy_mode_enum = postgresql.ENUM('Chalk', 'Balanced', 'Contrarian', name='strategy_mode_enum', create_type=True)
        strategy_mode_enum.create(conn)
    
    # Get the enum type (whether newly created or existing)
    strategy_mode_enum = postgresql.ENUM('Chalk', 'Balanced', 'Contrarian', name='strategy_mode_enum', create_type=False)
    
    # Create generated_lineups table
    op.create_table(
        'generated_lineups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('week_id', sa.Integer(), nullable=False),
        sa.Column('lineup_number', sa.Integer(), nullable=False),
        sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('total_salary', sa.Integer(), nullable=False),
        sa.Column('projected_score', sa.Float(), nullable=False),
        sa.Column('avg_ownership', sa.Float(), nullable=True),
        sa.Column('strategy_mode', strategy_mode_enum, nullable=False),
        sa.Column('weight_profile_id', sa.Integer(), nullable=True),
        sa.Column('optimization_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['weight_profile_id'], ['weight_profiles.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('lineup_number BETWEEN 1 AND 20', name='check_lineup_number_range'),
        sa.CheckConstraint('total_salary BETWEEN 0 AND 50000', name='check_total_salary_range'),
        sa.CheckConstraint('projected_score >= 0', name='check_projected_score_positive'),
        sa.CheckConstraint('avg_ownership BETWEEN 0 AND 1 OR avg_ownership IS NULL', name='check_avg_ownership_range')
    )
    
    # Create indexes for efficient queries
    op.create_index('idx_generated_lineups_week_id', 'generated_lineups', ['week_id'])
    op.create_index('idx_generated_lineups_week_lineup', 'generated_lineups', ['week_id', 'lineup_number'])
    op.create_index('idx_generated_lineups_strategy_mode', 'generated_lineups', ['strategy_mode'])
    op.create_index('idx_generated_lineups_created_at', 'generated_lineups', ['created_at'])


def downgrade() -> None:
    """Drop generated_lineups table and enum type."""
    op.drop_index('idx_generated_lineups_created_at', table_name='generated_lineups')
    op.drop_index('idx_generated_lineups_strategy_mode', table_name='generated_lineups')
    op.drop_index('idx_generated_lineups_week_lineup', table_name='generated_lineups')
    op.drop_index('idx_generated_lineups_week_id', table_name='generated_lineups')
    op.drop_table('generated_lineups')
    
    # Drop enum type
    op.execute("DROP TYPE IF EXISTS strategy_mode_enum")

